### PR TITLE
fix: allow returning, number and boolean as well

### LINKED ISSUE #48: is it necessary?
image

1. Have been confirmed type is object
2. In my opinion，val !== void 0 is not necessary

There are other applications for this part of the code ？

Pray for god's guidance~~~

### PR DESCRIPTION
**Pull request by danielroe**
resolves #48

This enables us to send a response for:

* boolean
* number
* bigint

We may wrongly return a response for functions & symbols. Though likely that's a user error rather than something h3 should check for.

### CODE REVIEW

**Comment by pi0** [comment]
It would be better if we check already resolved type against JSON-safe values rather than assuming all values as response

File: src/app.ts [hunk 1]
```diff
@@ -114,7 +114,7 @@ export function createHandle (stack: Stack, options: AppOptions): PHandle {
       const type = typeof val
       if (type === 'string') {
         return send(res, val, MIMES.html)
-      } else if (type === 'object' && val !== undefined) {
+      } else if (['bigint', 'number', 'boolean', 'object'].includes(type)) {
```
Comment (pi0) [inline src/app.ts:117]: For maximum performance, we could avoid iteration and add 4 `==` checks.

**Comment by pi0** [comment]
Removed bigint. JSON.parse seems unable to handle bigint by default (https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin)

File: src/app.ts [hunk 2]
```diff
@@ -114,7 +114,11 @@ export function createHandle (stack: Stack, options: AppOptions): PHandle {
       const type = typeof val
       if (type === 'string') {
         return send(res, val, MIMES.html)
-      } else if (type === 'object' && val !== undefined) {
+      } else if (
+        type === 'object'
```
Comment (danielroe) [inline src/app.ts:118]:
```suggestion
        type === 'object' ||
```
