### PR TITLE
fix(getRequestIP): use first address of `x-forwarded-for` header

### LINKED ISSUE #588: `xForwardedFor` returns the last IP address in the `X-Forwarded-For` header
### Environment

Node: v18.16.0
h3 1.9.0

### Reproduction

Call `getRequestIP(event, { xForwardedFor: true })` in an application behind a proxy server.

### Describe the bug

When calling `getRequestIP(event, { xForwardedFor: true })`, the last IP address in the list is returned instead of the first one (the client's IP address), when I assume the first one should be.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

resolves #588

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/utils/request.ts [hunk 1]
```diff
@@ -209,7 +209,7 @@ export function getRequestIP(
   if (opts.xForwardedFor) {
     const xForwardedFor = getRequestHeader(event, "x-forwarded-for")
```
Comment (pi0) [inline src/utils/request.ts:210]:
```suggestion
    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax
    const xForwardedFor = getRequestHeader(event, "x-forwarded-for")
```
